x-defaults: &apiServiceDefaults
  init: true
  tty: true
  command: npm run server
  env_file:
    - .env
  networks:
    - gold-v2-server

networks:
  gold-v2-server:

services:
  redis:
    container_name: gold-v2-redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - gold-v2-server
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./redis-data:/data
    command: sh -c "redis-server --requirepass $REDIS_PASSWORD"

  api-server:
    <<: *apiServiceDefaults
    container_name: gold-v2-user-auth-local
    ports:
      - '3000:3000'
      - '9000:9000'
    build:
      args:
        APP: user-auth
        START_COMMAND: server
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app/
      - /node_modules
