name: Deployment
run-name: Deploy to ${{ github.ref_name }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        type: choice
        options:
          - 'dev'
          - 'qa'
          - 'feature'
          - 'uat'
          - 'prod'

      service:
        description: Service
        required: true
        type: choice
        options:
          - 'all'
          - 'gateway'
          - 'user-auth'
          - 'communication'
          - 'activity-log'
          - 'network'

  push:
    branches: [dev, qa, uat, prod]

jobs:
  detect-changed-files-and-environment:
    name: Detect file changes and determine environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine environment
        run: |
          is_manual_run=$(echo ${{ contains(github.event_name, 'workflow_dispatch') }})

          if [ $is_manual_run == 'true' ]; then
            app_env=${{ github.event.inputs.environment }}
          else
            app_env=${{ github.ref_name }}
          fi

          echo "app_env=${app_env}" >> $GITHUB_ENV

          echo "Environment: $app_env"

      - uses: dorny/paths-filter@v3
        if: github.event_name != 'workflow_dispatch'
        id: changes
        with:
          base: ${{ github.ref_name || 'dev' }}
          filters: |
            gateway:
              - 'apps/gateway/**'
            user-auth:
              - 'apps/user-auth/**'
            communication:
              - 'apps/communication/**'
            activity-log:
              - 'apps/activity-log/**'
            network:
              - 'apps/network/**'

      - name: Set Output
        id: changed-services
        run: |
          is_manual_run=$(echo ${{ contains(github.event_name, 'workflow_dispatch') }})
          all_services="gateway,user-auth,activity-log,communication,network"
          CHANGES=${{ toJson(steps.changes.outputs.changes) }}

          if [ $is_manual_run == 'true' ]; then
            input_services=${{ github.event.inputs.service }}

            if [ $input_services == 'all' ]; then
              input_services=$all_services
            fi

            converted_inputs=$( jq -nc --arg input_services "$input_services" '$input_services | split(",")' )
            CHANGES=$converted_inputs
          fi


          echo "changes: $CHANGES"
          echo "changed_services=${CHANGES}" >> $GITHUB_ENV

    outputs:
      services: ${{ env.changed_services }}
      app_env: ${{ env.app_env }}

  deploy:
    needs: [detect-changed-files-and-environment]
    if: ${{ needs.detect-changed-files-and-environment.outputs.services != '[]' }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.detect-changed-files-and-environment.outputs.app_env }}
    permissions:
      id-token: write
      contents: read
    strategy:
      max-parallel: 5 # Run jobs in matrix sequentially.
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.detect-changed-files-and-environment.outputs.services) }}
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Set environment
        run: |
          environment=${{ needs.detect-changed-files-and-environment.outputs.app_env }}
          echo "Setting environment to $environment"
          echo "app_env=${environment}" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache docker build setup
        uses: actions/cache@v4
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}

      - name: Authenticate with AWS ECR
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::555906212677:role/oidc-role
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t ${{ matrix.service }}-${{ env.app_env }} --build-arg APP=${{ matrix.service }} --build-arg START_COMMAND=start .
          docker tag ${{ matrix.service }}-${{ env.app_env }}:latest ${{ secrets.ecr_repo_name }}/${{ matrix.service }}-${{ env.app_env }}:latest
          docker push ${{ secrets.ecr_repo_name }}/${{ matrix.service }}-${{ env.app_env }}:latest

      - name: Test
        run: |
          echo "/home/ubuntu/${{ env.app_env }}/${{ matrix.service }}"

      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}
          working-directory: /home/ubuntu/
          command: bash ${{ matrix.service }}.sh
          comment: Deployed!
      - name: Get the outputs
        run: echo "The Command id is ${{ steps.ssm.outputs.command-id }}"
