name: Sync
on:
  push:
    branches:
      - prod
      - preprod
      - uat
      - qa

jobs:
  sync-branches:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 12

      - name: Opening pull request from prod
        if: github.event_name == 'push' && github.ref == 'refs/heads/prod'
        id: pull-prod
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'prod'
          TO_BRANCH: 'preprod'
          PULL_REQUEST_TITLE: 'Sync: prod -> preprod'
          PULL_REQUEST_BODY: "New code has just landed in prod so let's bring preprod up to speed!"
          REVIEWERS: '["pragyann1"]'
          CONTENT_COMPARISON: true

      - name: Opening pull request from preprod
        if: github.event_name == 'push' && github.ref == 'refs/heads/preprod'
        id: pull-preprod
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'preprod'
          TO_BRANCH: 'uat'
          PULL_REQUEST_TITLE: 'Sync: preprod -> uat'
          PULL_REQUEST_BODY: "New code has just landed in preprod so let's bring uat up to speed!"
          REVIEWERS: '["pragyann1"]'
          CONTENT_COMPARISON: true

      - name: Opening pull request from uat
        if: github.event_name == 'push' && github.ref == 'refs/heads/uat'
        id: pull-uat
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'uat'
          TO_BRANCH: 'qa'
          PULL_REQUEST_TITLE: 'Sync: uat -> qa'
          PULL_REQUEST_BODY: "New code has just landed in uat so let's bring qa up to speed!"
          REVIEWERS: '["pragyann1"]'
          CONTENT_COMPARISON: true

      - name: Opening pull request from qa
        if: github.event_name == 'push' && github.ref == 'refs/heads/qa'
        id: pull-qa
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'qa'
          TO_BRANCH: 'dev'
          PULL_REQUEST_TITLE: 'Sync: qa -> dev'
          PULL_REQUEST_BODY: "New code has just landed in qa so let's bring dev up to speed!"
          REVIEWERS: '["pragyann1"]'
          CONTENT_COMPARISON: true
